version: '3.7'
networks:
  dev-network:
    driver: bridge
services:
  ecommerce-service:
    image: ecommerce-service
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - dev-network
    depends_on:
      - postgres
    environment:
      DB_USER: ecomm_user
      DB_PASSWORD: uKiTgHCM&51
  postgres:
    image: postgres:14.12
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_container:/var/lib/postgresql/data
    networks:
      - dev-network
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: ecomm_user
      POSTGRES_PASSWORD: uKiTgHCM&51

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/data/pgadmin
    networks:
      - dev-network

volumes:
  postgres_data_container:
  pgadmin_data:
